services:
  - type: web
    name: cms_dichvu
    env: node
    plan: starter
    buildCommand: npm run install && npm run build
    startCommand: npm start
    autoDeploy: false
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: strapi
    plan: basic-256mb
    diskSizeGB: 1